input {
  beats {
    port => 5044
  }
}

filter {
  if [message] =~ /^\{/ {
    json {
      source => "message"
    }
    date {
      match => ["timestamp", "ISO8601"]
      target => "@timestamp"
    }
  }

  mutate {
    add_field => {
      "pipeline_run_id" => "%{[pipeline_run_id]}"
      "environment" => "local"
    }
    remove_field => ["agent", "ecs", "input", "log", "host"]
  }
}

output {
  elasticsearch {
    hosts => ["elasticsearch:9200"]
    index => "pipeline-logs-%{+YYYY.MM.dd}"
  }
  stdout {
    codec => rubydebug
  }
}
